apiVersion: v1
kind: Service
metadata:
  name: {{ include "dummy-redis.fullname" . }}
  labels:
    {{- include "dummy-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: resp
      protocol: TCP
      name: resp
  selector:
    {{- include "dummy-redis.selectorLabels" . | nindent 4 }}
